# Generated by Django 5.1.6 on 2025-02-18 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suddidotapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsarticle',
            name='category',
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='categories',
            field=models.ManyToManyField(related_name='articles', to='suddidotapp.category'),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='is_trending',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
