# Generated by Django 5.1.6 on 2025-02-18 13:20

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suddidotapp', '0002_remove_newsarticle_category_newsarticle_categories_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
    ]
