# Generated by Django 5.1.6 on 2025-02-24 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suddidotapp', '0005_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='upvotes',
        ),
    ]
