# Generated by Django 5.1.6 on 2025-02-25 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suddidotapp', '0008_alter_newsarticle_published_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='image',
            field=models.ImageField(upload_to='news_images/'),
        ),
    ]
